name: Manual Publish

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project to release (e.g. conditional-forms)'
        required: true
      version:
        description: 'Version bump (patch, minor, major, or 1.2.3)'
        required: false
        default: ''
  release:
    types: [published]
jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run Nx Release
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.version }}" != "" ]]; then
            npx nx release version ${{ github.event.inputs.version }} --git-commit --git-tag --git-push
          else
            npx nx release version --git-commit --git-tag --git-push
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package with version number
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version != '' }}
        run: npx nx build ${{ github.event.inputs.project }} --version ${{ github.event.inputs.version }} --skip-nx-cache --parallel=3
      - name: Build package without version number
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.version == '' }}
        run: npx nx affected -t build --skip-nx-cache --parallel=3

      - name: Publish to npm
        run: npx nx release publish --yes --skip-nx-cache
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
