name: Publish to npm

on:
  push:
    tags:
      - 'conditional-forms@*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: npm

      - run: npm ci --legacy-peer-deps

      - name: Build packages
        run: npx nx run conditional-forms:build

      - name: Publish to npm
        run: npx nx release publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
